name: Create and publish a Docker image to ECR
on:
  push:
    branches: ['main', 'develop']

env:
  IMAGE_REPO_NAME: 767828741221.dkr.ecr.ap-southeast-1.amazonaws.com/signal/signal-server
  DOCKER_BUILDKIT: 0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO_NAME }}

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV


      - name: Build Docker Image (without BuildKit)
        run: |
          export DOCKER_BUILDKIT=0
          docker build -t $IMAGE_REPO_NAME:${{ env.TIMESTAMP }} .

      - name: Push Docker Image to ECR
        run: |
          docker push $IMAGE_REPO_NAME:${{ env.TIMESTAMP }}